### ISSUE TITLE
Add supported OS in the readme

### ISSUE THREAD

**Issue by chmike** [agnivade/funnel#29]
In which OS can Funnel be used ? Can it be used on Windows ? A few words on this in the readme would help.

Looking at the prebuild binaries, it seam that funnel can't be used on windows. Is that right ? 

If not, how difficult would it be to add support for windows ?

**Comment by agnivade** [comment]
The initial versions supported windows. But later, I started to use syslog for sending funnel logs because that felt more natural. As syslog is not supported on windows, funnel doesn't work on windows -
https://golang.org/pkg/log/syslog/#pkg-note-BUG

To make it work on windows, just replace the syslog writer with another logging library which atleast has an `Err()` method implemented. I only call `Err()` from my code. So, essentially you just need to modify a single line.
