### ISSUE TITLE
An example of docker-compose?

### ISSUE THREAD

**Issue by drozzy** [agnivade/funnel#38]
Could you provide an example of how I could setup my docker services to log to funnel automatically, using docker-compose configuration?

I could explain more if needed!
Thanks.

**Comment by agnivade** [comment]
I guess you want to route your logs from inside docker containers to remote targets ? You will need to update your `Dockerfile` and put the funnel binary (and any custom config, if you want) inside your docker image.

Does that answer your question ?

I don't see a specific use-case for docker-compose since you are not linking 2 containers here.

**Comment by drozzy** [comment]
I was thinking something like using logspout to route all logs.

**Comment by drozzy** [comment]
For example, here is what I came up with for OKLogger:
https://gist.github.com/drozzy/06d1b2e48beac9527f5777cd1cd02492

**Comment by drozzy** [comment]
Oh, ok! Thanks.
